// Built from tag arkiv

using System;

namespace FINT.Model.Kultur.Kulturminnevern
{
	public enum KulturminnevernActions
    {
	
	GET_DISPENSASJONAUTOMATISKFREDAKULTURMINNE,
	GET_ALL_DISPENSASJONAUTOMATISKFREDAKULTURMINNE,
	UPDATE_DISPENSASJONAUTOMATISKFREDAKULTURMINNE,
	GET_TILSKUDDFARTOY,
	GET_ALL_TILSKUDDFARTOY,
	UPDATE_TILSKUDDFARTOY,
	GET_TILSKUDDFREDAHUSPRIVATEIE,
	GET_ALL_TILSKUDDFREDAHUSPRIVATEIE,
	UPDATE_TILSKUDDFREDAHUSPRIVATEIE
    }
}
